apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app: helm
    type: base-app
    env: prod
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: v0.15.2
    chart: metallb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-ip-pool
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mdp-eg-org/infra-mdp
    targetRevision: HEAD
    path: argocd-base-apps/metallb/config

