apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdkss-service
  namespace: argocd
  labels:
    env: dev
spec:
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true
  destination:
    namespace: internetbanking-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/mdp-eg-org/infra-mdp
    targetRevision: HEAD
    path: apps/sdkss-service/overlay/dev
---