resources:
- metallb/application.yaml
- traefik/external-application.yaml
- traefik/internal-application.yaml
- cert-manager/application.yaml
- longhorn/application.yaml
- external-secrets/application.yaml
