apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: middleware-ingress
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
spec:
  ingressClassName: traefik-external
  rules:
    - host: placeholder-host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internetbanking-middleware
                port:
                  number: 8080
  tls:
    - hosts:
        - placeholder-host
      secretName: middleware-tls