apiVersion: v1
kind: Service
metadata:
  name: internetbanking-middleware
spec:
  selector:
    app: internetbanking-middleware
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
