apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-external
  namespace: argocd
  labels:
    app: helm
    type: base-app
    env: prod
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://github.com/mdp-eg-org/infra-mdp'
      targetRevision: main
      ref: values
    - repoURL: 'https://traefik.github.io/charts'
      chart: traefik
      targetRevision: 37.0.0
      helm:
        valueFiles:
        - $values/argocd-base-apps/traefik/values.yaml
        - $values/argocd-base-apps/traefik/values-external.yaml
