ingressClass:
  enabled: true
  name: "traefik-internal"
  isDefaultClass: false

additionalArguments:
  - "--providers.kubernetesingress.ingressclass=traefik-internal"
  - "--ping"

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    nodePort: 32081

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    nodePort: 32444

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: "internal-pool"
